export const TYPE_CONTAINER = {
  APP: Symbol('APP'),
  HOME: Symbol('HOME'),
  MOVIE_COMING: Symbol('MOVIE_COMING'),
  MOVIE_SHOWING: Symbol('MOVIE_SHOWING'),
  MOVIE_SEARCH: Symbol('MOVIE_SEARCH'),

  APP_CONNECTED: Symbol('APP_CONNECTED'),
  HOME_CONNECTED: Symbol('HOME_CONNECTED'),
  MOVIE_COMING_CONNECTED: Symbol('MOVIE_COMING_CONNECTED'),
  MOVIE_SHOWING_CONNECTED: Symbol('MOVIE_SHOWING_CONNECTED'),
  MOVIE_SEARCH_CONNECTED: Symbol('MOVIE_SEARCH_CONNECTED')
}
