export const TYPE_CONTAINER = {
  HOME: Symbol('HOME'),
  MOVIE_COMING: Symbol('MOVIE_COMING'),
  MOVIE_SHOWING: Symbol('MOVIE_SHOWING'),
  MOVIE_SEARCH: Symbol('MOVIE_SEARCH'),
  USER_DETAIL: Symbol('USER_DETAIL'),
  DRAWER_CONTENT: Symbol('DRAWER_CONTENT')
}
